[package]
name = "database"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
pulldown-cmark = {version = "0.13"} 
sqlx = {version= "0.8.6", features = ["sqlite", "runtime-tokio"]} 

